#!/usr/bin/env python
# -*- coding: utf-8 -*-

import src.interpreter as intp
from optparse import OptionParser
import sys
import traceback

def pydrop(i):
    import os
    global undrop
    global curr
    curr = i

    os.environ["PYTHONINSPECT"] = "1"

    def undrop():
        run_console(i)


def import_readline():
    try:
        import readline
    except ImportError:
        pass

    def completer(text, state=0):
        if text:
            m = [i for i in intp.curr.keys() if i.startswith(text)]
        else:
            m = intp.curr.keys()[:]

        try:
            return m[state]
        except IndexError:
            return None

    readline.set_completer(completer)
    readline.parse_and_bind("tab: complete")
    return readline

def run_console(i):
    import src.lexer as lexer
    import src.analyze as analyze
    import_readline()

    try:
        t = ""
        while True:
            t = raw_input("oranj> ") + "\n"
            while not lexer.isdone(t):
                t += raw_input("     > ") + "\n"

            try:
                r = intp.run(t, i)

                if r == None: pass
                elif r.ispy() and r.topy() == None: pass
                else:
                    print repr(r)
            except intp.PyDropI: raise
            except intp.DropI:
                break # This will happen when you #!undrop
            except Exception, e:
                traceback.print_exc()
    except EOFError:
        print
    except KeyboardInterrupt:
        print
        sys.exit()
    except intp.PyDropI:
        print "Dropping down to python console. Call undrop() to return."
        pydrop(i)

def parse_args():
    parser = OptionParser()
    parser.add_option("-r", "--readin", action="store_true", help="Read input from stdin until EOF, then execute it", default=False)
    parser.add_option("-t", "--test", help="Test a component (parser, lexer, analyzer). oranj -t p|l|a", default="")
    opts, args = parser.parse_args()
    child = []

    if args:
        child = sys.argv[sys.argv.index(args[0]):]
        opts = parser.parse_args(sys.argv[:sys.argv.index(args[0])])[0]

    return opts, args, child

if __name__ == "__main__":
    base_i = intp.Interpreter()
    opts, args, child = parse_args()

    if child:
        intp.run(open(child[0]).read(), base_i)
    elif opts.readin:
        intp.run(sys.stdin.read())
    elif opts.test:
        import_readline()
        if opts.test == "a":
            import src.analyze as analyze
            analyze._test()
        elif opts.test == "p":
            import src.parser as parser
            parser._test()
        elif opts.test == "l":
            import src.lexer as lexer
            lexer._test()
    else:
        intp.Interpreter.run_console = run_console
        run_console(base_i)
